-- ==========================================
-- Supabase Schema for Myanmar Kyar Kwet
-- ==========================================

-- 1. Create Tables

-- Rooms (For Multiplayer matches)
CREATE TABLE IF NOT EXISTS public.rooms (
  id TEXT PRIMARY KEY,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Profiles (For Authenticated Users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT,
  avatar_url TEXT,
  user_code TEXT UNIQUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Guest Profiles (For Guest Users)
CREATE TABLE IF NOT EXISTS public.guest_profiles (
  id TEXT PRIMARY KEY,
  display_name TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Friendships (Authenticated users)
CREATE TABLE IF NOT EXISTS public.friendships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  addressee_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Guest Friend Requests (For cross-device or Guest users)
CREATE TABLE IF NOT EXISTS public.guest_friend_requests (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  from_guest_id TEXT,
  from_guest_name TEXT,
  to_uid UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Friend Messages
CREATE TABLE IF NOT EXISTS public.friend_messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  from_uid TEXT NOT NULL,
  to_uid TEXT NOT NULL,
  from_name TEXT,
  message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Room Invites
CREATE TABLE IF NOT EXISTS public.room_invites (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  from_uid UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  to_uid UUID NOT NULL, -- can be guest or auth
  from_name TEXT,
  room_code TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User Status (Online/Offline)
CREATE TABLE IF NOT EXISTS public.user_status (
  uid TEXT PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'offline',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- 2. Enable Row Level Security (RLS)
-- ==========================================
-- (Setting completely permissive for ease of use, as it was running smoothly before.
-- In production, you would tighten these rules based on auth.uid())

ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_friend_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friend_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_status ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow ALL on rooms" ON public.rooms FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on guest_profiles" ON public.guest_profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on friendships" ON public.friendships FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on guest_friend_requests" ON public.guest_friend_requests FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on friend_messages" ON public.friend_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on room_invites" ON public.room_invites FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow ALL on user_status" ON public.user_status FOR ALL USING (true) WITH CHECK (true);

-- ==========================================
-- 3. Setup Trigger for Auth Users
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', 'Player ' || substr(new.id::text, 1, 4)),
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 4. Enable Realtime
-- ==========================================
-- Add tables to the realtime publication
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;

ALTER PUBLICATION supabase_realtime ADD TABLE public.rooms;
ALTER PUBLICATION supabase_realtime ADD TABLE public.friendships;
ALTER PUBLICATION supabase_realtime ADD TABLE public.guest_friend_requests;
ALTER PUBLICATION supabase_realtime ADD TABLE public.friend_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.room_invites;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_status;
